default:
  path:
    data: "/Volumes/shlab/Projects/CSN/data"
    extracted: "extracted"
    raw: "raw"
    clean: "clean"
    eyetracker: "eyetracker"
    behavioral: "behavioral"
    questionnaire: "questionnaire"
  extracted_files:
    eyetracker_ioevent_csv: "ioevent.csv"
    eyetracker_recordings_csv: "recordings.csv"
    eyetracker_event_csv: "fevent.csv"
    eyetracker_sample_csv: "fsample.csv"
  participants:
    id_prefix: "CSN"
    id_pad_character: "0"
    id_pad_length: 3
    total: 57
    incomplete: 7

# Ari's Macbook System User
metis:
  inherits: default

# Peter's Macbook System User
# TODO:
# user:
#   inherits: default
